# Site settings
title: BodisT pages
description: Technical documentation, blog posts, and presentations
author: Tamas Bodis
url: https://bodis.github.io
baseurl: /website

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

# Exclude from processing
exclude:
  - .vscode/
  - .claude/
  - .git/
  - .gitignore
  - README.md

# Collections for different content types
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
  docs:
    output: true
    permalink: /docs/:path/

# Default layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"
  - scope:
      path: "presentations"
    values:
      layout: false

# Using custom layouts instead of theme
